# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo apt-get update; sudo apt-get install ghostscript
            pipenv sync --dev


      - save_cache:
          paths:
            - ./local
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      # run tests!
      - run:
          name: run tests
          environment:
            MPLBACKEND: "agg"
          command: pipenv run pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - /test-.*/
